### ISSUE TITLE
Black List

### ISSUE THREAD

**Issue by raubv0gel** [epiphyt/embed-privacy#126]
### What feature are you requesting?

Is it possible to add a kind of black list?

### Why is this feature necessary?

Look at [https://maxheckel.de/neuigkeiten/ich-unterstuetze-max-heckel/](https://maxheckel.de/neuigkeiten/ich-unterstuetze-max-heckel/) please. The embed is blocked, but I don’t want this to be blocked because the domain/service is owned by myself.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
This has already been implemented in some way:

You can create your own embed provider and explicitly disable it so that embed from this provider won’t get blocked.

Just head over to **Settings > Embed Privacy > Manage embeds** to create a new embed provider. Then, use the regex `/ich-unterstuetze\.de/` and explicitly check the checkbox below to disabled the embed provider.

**Comment by raubv0gel** [comment]
@MatzeKitt, many thanks! I will have a try.
