### ISSUE TITLE
Do not polute global JS namespace

### ISSUE THREAD

**Issue by kraftner** [epiphyt/embed-privacy#182]
### Bug/Problem

There currently are multiple JS functions defined in the global namespace. To make things worse they also have very generic names. They are also taken from stackoverflow which makes it even more likely to have collisions with other peoples code.

- `get_cookie`
- `htmlentities_decode`
- `remove_cookie`
- `set_cookie`

https://github.com/epiphyt/embed-privacy/blob/2cf319a685b1320dc17cdbb677191bcd7e3656f0/assets/js/embed-privacy.js#L286-L346

### Steps to reproduce

1. Go to the frontend of a site with Embed Privacy enabled
2. Open developer console
3. Start typing e.g. `get_ cookie` to see that they are defined in the global namespace.

### Version

1.7.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kraftner** [comment]
The easiest solution probably is to wrap the whole file into an [Immediately Invoked Function Expression](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) to have everything in its own scope.
I do not expect any breaking changes to be caused by that. If you want I can also offer to create a PR for that.

**Comment by MatzeKitt** [comment]
This should only affect dev environments with `WP_DEBUG` enabled, though, since they’re no more global as soon as compiled (there the IIFE is already in use).

Currently, I consider this a minor issue as it doesn’t effect production sites.

However, it’s already planned to refactor the JavaScript in version 2.0 since it’s a breaking change. So I added this to the list on #67.

Thank you for pointing out the problem. 🤗

**Comment by MatzeKitt** [comment]
No problem, I didn’t have it on the list. Better this way than another. 🙂
