### ISSUE TITLE
Fix invalid HTML through style tags

### ISSUE THREAD

**Issue by MatzeKitt** [epiphyt/embed-privacy#198]
### Bug/Problem

https://wordpress.org/support/topic/inline-styling-appears-to-break-html-validation/

### Steps to reproduce

Validate any page Embed Privacy is active on

### Version

1.8.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
Unfortunately, this is probably not fixable since the replacement takes place after the `wp_head` action and thus any style is added to the footer. I would need to process the content before its output, which is problematic since the necessary filter haven’t been executed at this point yet.

**Comment by arnowelzel** [comment]
As far I see it, the issue can be fixed. There is no need to output styles which refer to a DIV inside that very element instead of using inline styles.

**Comment by MatzeKitt** [comment]
Inline-Styles are highly discouraged since they’re hard to overwrite and rather unperformant at all.

**Comment by arnowelzel** [comment]
A style for a generated(!) ID is also hard to overwrite. And having invalid HTML is worse than having discouraged parts in the output.

**Comment by arnowelzel** [comment]
I did not realize, that there is already a commit for this which solves that (https://github.com/epiphyt/embed-privacy/commit/52efe794b8c8beb2b2cb6f53d9a12d79086253df).

**Comment by arnowelzel** [comment]
I modified the code for my own website, example: https://arnowelzel.de/en/pinecil-v2-with-bluetooth

About performance:

Every style is only valid for one single element only. Tere is no performance gain in putting all the dynamically created rules into a separate `<style>` element in the document instead of having the same rules as inline style each element.

The browser has to parse every single style on every page anyway since the styles are not global rules which are loaded from an external and thus cacheable resource like the themes `style.css`. They use a unique selector like `[data-embed-id="oembed_<ID>"]` where `<ID>` is a unique ID and not a reusable selector like `.embed-privacy-inner` or `.embed-privacy-logo`.

So - yes in general I agree having styles which would get repeated multiple times as inline style makes no sense and should be replaced with a class. But in this case I think, it makes no difference at all.
