### ISSUE TITLE
Disabling YouTube in epi_embed post type does not apply for `www.youtube-nocookie.com`

### ISSUE THREAD

**Issue by civilblur** [epiphyt/embed-privacy#203]
### Bug/Problem

When disabling the YouTube embed via epi_embed post type, it will continue to match YouTube embeds if you're embedding with the domain `www.youtube-nocookie.com`. This domain is utilized for loading YouTube videos without introducing cookies until user interaction (although, one should not rely on the privacy effects of this).

Currently, the regex for YouTube is missing the no-cookie YouTube links and only matches for e.g.:
- https://www.youtube.com/watch?v=abc123
- http://youtu.be/xyz456
- https://m.youtube.com/v/789def

**Suggestion:**
Change regex from:
`/https?:\/\/(?:.+?.)?youtu(?:.be|be.com)/`
to:
`/https?:\/\/(?:.+?.)?youtu(?:.be|be\.com|be-nocookie\.com)/`

The suggested change will include embeds such as: `https://www.youtube-nocookie.com/embed/abc123`

---

Thank you for your ongoing efforts in crafting such an elegant and straightforward solution!

### Steps to reproduce

1. Go to "Settings -> Embed Privacy"
2. Navigate to "Manage embed"
3. Enter the epi_embed post "YouTube"
4. Check "Disable embed provider" and save

### Version

1.8.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatzeKitt** [comment]
This works as expected for me, since the YouTube embed provider doesn’t handle embeds to youtube-nocookie.com at all. Embed Privacy just transforms all embeds to YouTube to youtube-nicotine.com if the embed provider is enabled. 

If disabled, youtube-nocookie.com is another embed provider. If you want to allow such embeds without being blocked by Embed Privacy, you just need to create an own embed provider in **Settings > Embed Privacy > Manage embeds** and then disable this provider. 🙂 

This is by design since (with a few exceptions) Embed Privacy only handles oEmbed providers implemented in WordPress by default. And youtube-nocookie.com is no such oEmbed provider.

**Comment by MatzeKitt** [comment]
I appreciate the effort. ❤️
