### ISSUE TITLE
Add option to use JavaScript for detecting an always active provider

### ISSUE THREAD

**Issue by MatzeKitt** [epiphyt/embed-privacy#7]
To be able to work with caching plugins, there should be an option to allow detecting of an always active provider via JavaScript.

Related discussion: https://github.com/epiphyt/embed-privacy/issues/2#issuecomment-735468079

**Comment by goaround** [comment]
One more suggestion: If check the always active provider completly client side with JavaScript and don't want to do this on the server level, use localStorage instead of Cookies. The API is much simpler and cleaner: https://developer.mozilla.org/de/docs/Web/API/Window/localStorage

Than the JavaScript code will be even less then before because you don't need all these Cookie-Helper-Functions!

**Comment by MatzeKitt** [comment]
Please add this as a separate suggestion. 🙂
